### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by adybdahl** [richmarisa/bingo-display#1]
Hello,

I would like to fork this project and make a few cosmetic adjustments to the board. However, this project does not currently have a LICENSE file, so I'm not sure if this is allowed.

Under which license is this project distributed?

You can find more information about software licenses here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by richmarisa** [comment]
MIT License added.  Thank you.
